{
 "title": "Test Result",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "testid", "label": "Test ID", "query": { "query": "label_values(testid)" } },
   { "name": "scenario", "label": "scenario", "query": { "query": "label_values(scenario)" } }
  ]
 },
 "panels": [
  {
   "title": "Per process performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top processes by Used  memory",
     "type": "graph",
     "description": "Memory Used by Processes, counted as Resident Memory + Space used in Swap Space",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "topk(5,(\r\n(avg_over_time(namedprocess_namegroup_memory_bytes{memtype=\"swapped\"}[$__interval])+ ignoring (memtype) avg_over_time(namedprocess_namegroup_memory_bytes{memtype=\"resident\"}[$__interval]))\r\nor\r\n(avg_over_time(namedprocess_namegroup_memory_bytes{memtype=\"swapped\"}[5m])+ ignoring (memtype) avg_over_time(namedprocess_namegroup_memory_bytes{memtype=\"resident\"}[5m]))\r\n)) / on() group_left() node_memory_MemTotal_bytes",
       "legendFormat": "{{groupname}}"
      }
     ]
    },
    {
     "title": "Top processes by Total CPU use",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "topk(2,(sum (rate(namedprocess_namegroup_cpu_seconds_total[$__rate_interval])  )without (mode) > 0))",
       "legendFormat": "{{groupname}}"
      }
     ]
    },
    {
     "title": "Top processes by Bytes Read",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "topk(1,(rate(namedprocess_namegroup_read_bytes_total[5m]) or irate(namedprocess_namegroup_read_bytes_total[5m])))  / on() group_left() sum by(instance) (rate(node_disk_read_bytes_total[5m]))",
       "legendFormat": "{{groupname}}"
      }
     ]
    },
    {
     "title": "Top processes by Bytes Written",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "topk(1,(rate(namedprocess_namegroup_write_bytes_total[5m]) or irate(namedprocess_namegroup_write_bytes_total[5m]))) / on() group_left() sum by(instance) (rate(node_disk_written_bytes_total[5m]))",
       "legendFormat": "{{groupname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Test Overall info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (status) (rate(k6_http_reqs{scenario = \"$scenario\"}[$__rate_interval]))",
       "legendFormat": "HTTP {{status}}"
      }
     ]
    },
    {
     "title": "VU over time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "k6_vus{testid=~\"$testid\"}"
      }
     ]
    },
    {
     "title": "RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "max(rate(k6_http_reqs{scenario=~\"$scenario\"}[$__rate_interval]))",
       "legendFormat": "Total requests rate"
      }
     ]
    },
    {
     "title": "Non-response HTTP reqs",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count(k6_http_reqs{testid=~\"$testid\",expected_response=\"true\"})"
      }
     ]
    },
    {
     "title": "Requests/second",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(k6_http_reqs{testid=~\"$testid\"}[1s]))"
      }
     ]
    },
    {
     "title": "Active VUs",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "k6_vus{testid=~\"$testid\"}"
      }
     ]
    },
    {
     "title": "VU and response time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "k6_vus{testid=~\"$testid\"}"
      },
      {
       "expr": "k6_group_duration_avg{testid=~\"$testid\", scenario=~\"$scenario\"}",
       "legendFormat": "{{group}}"
      }
     ]
    },
    {
     "title": "Iteration duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "k6_iteration_duration_avg{scenario=\"$scenario\"}",
       "legendFormat": "avg"
      },
      {
       "expr": "k6_iteration_duration_max{scenario=\"$scenario\"}",
       "legendFormat": "max"
      },
      {
       "expr": "k6_iteration_duration_min{scenario=\"$scenario\"}",
       "legendFormat": "min"
      },
      {
       "expr": "k6_iteration_duration_med{scenario=\"$scenario\"}",
       "legendFormat": "median"
      },
      {
       "expr": "k6_iteration_duration_p90{scenario=\"$scenario\"}",
       "legendFormat": "90 percentile"
      },
      {
       "expr": "k6_iteration_duration_p95{scenario=\"$scenario\"}",
       "legendFormat": "95 percentile"
      }
     ]
    },
    {
     "title": "Failed requests rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(k6_http_req_failed{scenario=\"$scenario\"})",
       "legendFormat": "Failed requests"
      }
     ]
    },
    {
     "title": "Requests by URL",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "count by (url) (k6_http_reqs{scenario=\"$scenario\"})"
      }
     ]
    },
    {
     "title": "Avg Response time (95th percentile)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(k6_http_req_duration_p95{testid=~\"$testid\",expected_response=\"true\"})\n"
      }
     ]
    },
    {
     "title": "HTTP errors",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count(k6_http_reqs{testid=~\"$testid\",expected_response=\"false\"})"
      }
     ]
    },
    {
     "title": "URLs",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "count by (url) (k6_http_reqs{testid=~\"$testid\"})",
       "legendFormat": "__auto",
       "rawSql": "SELECT\n  tags->>'url' AS \"URL\",\n  tags->>'method' AS \"method\",\n  CASE \n    WHEN (tags->>'status')::int = 0 AND (tags->>'error_code')::int >= 1000 AND (tags->>'error_code')::int <= 1099 THEN tags->>'error_code' || ' (General)'\n    WHEN (tags->>'status')::int = 0 AND (tags->>'error_code')::int = 1101 THEN tags->>'error_code' || ' (DNS no such host)'\n    WHEN (tags->>'status')::int = 0 AND (tags->>'error_code')::int = 1110 THEN tags->>'error_code' || ' (DNS blacklisted IP)'\n    WHEN (tags->>'status')::int = 0 AND (tags->>'error_code')::int >= 1100 AND (tags->>'error_code')::int <= 1199 THEN tags->>'error_code' || ' (DNS)'\n    WHEN (tags->>'status')::int = 0 AND (tags->>'error_code')::int = 1211 THEN tags->>'error_code' || ' (TCP connection timeout)'\n    WHEN (tags->>'status')::int = 0 AND (tags->>'error_code')::int = 1212 THEN tags->>'error_code' || ' (TCP connection refused)'\n    WHEN (tags->>'status')::int = 0 AND (tags->>'error_code')::int = 1213 THEN tags->>'error_code' || ' (TCP connection error)'\n    WHEN (tags->>'status')::int = 0 AND (tags->>'error_code')::int >= 1200 AND (tags->>'error_code')::int <= 1299 THEN tags->>'error_code' || ' (TCP)'\n    WHEN (tags->>'status')::int = 0 AND (tags->>'error_code')::int = 1311 THEN tags->>'error_code' || ' (TLS cert not matching hostname)'\n    WHEN (tags->>'status')::int = 0 AND (tags->>'error_code')::int >= 1300 AND (tags->>'error_code')::int <= 1399 THEN tags->>'error_code' || ' (TLS)'\n    WHEN (tags->>'status')::int = 0 AND (tags->>'error_code')::int >= 1600 AND (tags->>'error_code')::int <= 1699 THEN tags->>'error_code' || ' (HTTP/2)'\n    WHEN (tags->>'status')::int = 0 THEN tags->>'error_code'\n    ELSE tags->>'status'\n  END AS \"status\",\n  COUNT(*) AS count,\n  percentile_cont(0.95) WITHIN GROUP (ORDER BY value) AS \"95th\",\n  percentile_cont(0.99) WITHIN GROUP (ORDER BY value) AS \"99th\",\n  MAX(value) AS \"max\"\nFROM\n  samples\nWHERE\n  $__timeFilter(ts)\n  AND metric = 'http_req_duration'\n  AND (CASE WHEN $testid != '<all>' THEN tags->>'testid' = $testid ELSE true END)\nGROUP BY 1, 2, 3\nORDER BY 6 DESC\nLIMIT 100"
      }
     ]
    },
    {
     "title": "Response time (95th percentile)",
     "type": "timeseries",
     "description": "The 95th percentile response time of the target system, with success responses separated from error responses.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(k6_http_req_duration_p95{testid=~\"$testid\",expected_response=\"true\"})\n",
       "legendFormat": "Successful responses"
      },
      {
       "expr": "avg(k6_http_req_duration_p95{testid=~\"$testid\",expected_response=\"false\"})\n",
       "legendFormat": "Failed responses"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 41 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(k6_http_req_failed{url=~\"$url\",scenario=\"$scenario\",expected_response=\"false\"}) by (error)"
      }
     ]
    },
    {
     "title": "Error requests",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "k6_http_req_failed{testid=~\"$testid\", status != \"200\", status != \"302\"}",
       "legendFormat": "__auto",
       "rawSql": "SELECT\n  tags->>'url' AS \"URL\",\n  tags->>'method' AS \"method\",\n  CASE \n    WHEN (tags->>'status')::int = 0 AND (tags->>'error_code')::int >= 1000 AND (tags->>'error_code')::int <= 1099 THEN tags->>'error_code' || ' (General)'\n    WHEN (tags->>'status')::int = 0 AND (tags->>'error_code')::int = 1101 THEN tags->>'error_code' || ' (DNS no such host)'\n    WHEN (tags->>'status')::int = 0 AND (tags->>'error_code')::int = 1110 THEN tags->>'error_code' || ' (DNS blacklisted IP)'\n    WHEN (tags->>'status')::int = 0 AND (tags->>'error_code')::int >= 1100 AND (tags->>'error_code')::int <= 1199 THEN tags->>'error_code' || ' (DNS)'\n    WHEN (tags->>'status')::int = 0 AND (tags->>'error_code')::int = 1211 THEN tags->>'error_code' || ' (TCP connection timeout)'\n    WHEN (tags->>'status')::int = 0 AND (tags->>'error_code')::int = 1212 THEN tags->>'error_code' || ' (TCP connection refused)'\n    WHEN (tags->>'status')::int = 0 AND (tags->>'error_code')::int = 1213 THEN tags->>'error_code' || ' (TCP connection error)'\n    WHEN (tags->>'status')::int = 0 AND (tags->>'error_code')::int >= 1200 AND (tags->>'error_code')::int <= 1299 THEN tags->>'error_code' || ' (TCP)'\n    WHEN (tags->>'status')::int = 0 AND (tags->>'error_code')::int = 1311 THEN tags->>'error_code' || ' (TLS cert not matching hostname)'\n    WHEN (tags->>'status')::int = 0 AND (tags->>'error_code')::int >= 1300 AND (tags->>'error_code')::int <= 1399 THEN tags->>'error_code' || ' (TLS)'\n    WHEN (tags->>'status')::int = 0 AND (tags->>'error_code')::int >= 1600 AND (tags->>'error_code')::int <= 1699 THEN tags->>'error_code' || ' (HTTP/2)'\n    WHEN (tags->>'status')::int = 0 THEN tags->>'error_code'\n    ELSE tags->>'status'\n  END AS \"status\",\n  COUNT(*) AS count,\n  percentile_cont(0.95) WITHIN GROUP (ORDER BY value) AS \"95th\",\n  percentile_cont(0.99) WITHIN GROUP (ORDER BY value) AS \"99th\",\n  MAX(value) AS \"max\"\nFROM\n  samples\nWHERE\n  $__timeFilter(ts)\n  AND metric = 'http_req_duration'\n  AND (CASE WHEN $testid != '<all>' THEN tags->>'testid' = $testid ELSE true END)\nGROUP BY 1, 2, 3\nORDER BY 6 DESC\nLIMIT 100"
      }
     ]
    },
    {
     "title": "Response beakdown (95th percentile)",
     "type": "timeseries",
     "description": "Breakdown of response time into its constituent parts.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(k6_http_req_blocked_avg{testid=~\"$testid\"})",
       "legendFormat": "Blocked"
      },
      {
       "expr": "sum(k6_http_req_waiting_avg{testid=~\"$testid\"})",
       "legendFormat": "Waiting"
      },
      {
       "expr": "sum(k6_http_req_ending_avg{testid=~\"$testid\"})",
       "legendFormat": "Sending"
      },
      {
       "expr": "sum(k6_http_req_receiving_avg{testid=~\"$testid\"})",
       "legendFormat": "Receiving"
      },
      {
       "expr": "sum(k6_http_tls_handshaking_avg{testid=~\"$testid\"})",
       "legendFormat": "TLS handshaking"
      }
     ]
    },
    {
     "title": "Data transfer",
     "type": "timeseries",
     "description": "Data sent and received per second.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(k6_data_received{testid=~\"$testid\"}[10s])",
       "legendFormat": "Received"
      },
      {
       "expr": "rate(k6_data_sent{testid=~\"$testid\"}[10s])",
       "legendFormat": "Sent"
      }
     ]
    }
   ]
  }
 ]
}